### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mitchellporter** [seedante/CardAnimation#3]
What's the license for this?

**Comment by seedante** [comment]
en, MIT, I guess, as you like.

**Comment by mitchellporter** [comment]
@seedante Would you like me to submit a pull request with the MIT License added to the project?

**Comment by seedante** [comment]
No need for this, just an animation code for other's design.

**Comment by seedante** [comment]
Thank you for your advice, I just think there is no need for now.

**Comment by mitchellporter** [comment]
@seedante Just in case you're not aware, this can't be used in production for most apps without a proper license attached. Cheers.

**Comment by seedante** [comment]
@mitchellporter really? We have talk so mush enough to add license.
